/employee/role:
  get:
    summary: Retrieve a list of all roles
    responses:
      200:
        description: OK
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Role"
      