components:
  schemas:
    Account:
      type: object
      properties:
        accountId: 
          type: string
        firstName: 
          type: string
        lastName: 
          type: string
        email:
          type: string
        phoneNumber?: 
          type: string
        dateCreated: 
          type: string
        dateUpdated: 
          type: string
        roles:
          type: array
          items:
            $ref: "#/components/schemas/Role"