components:
  schemas:
    BookingAddon:
      type: object
      properties:
        bookingAddonId:
          type: string
        numberOfUnits:
            type: number
        addon:
          $ref: "#components/schemas/Addon"
          