components:
  schemas:
    PublicEmployee:
      type: object
      properties:
        employeeId:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        