  /customer/address/{customerAddressId}:
    patch:
      summary: edits an address
      consumes:
        - application/json
      parameters:
        - in: path
          name: customerAddressId   
          schema:
            type: integer
            minimum: 1
          description: uuid
        - in: body
          name: Req
          schema:
            type: object
            properties:
              address:
                type: object
                properties:
                  code:
                    type: string

      produces:
        - application/json
      responses:
        200:
          description: OK
        
        401:
            description: ACCESS_DENIED
        400:
            description: Bad input format
