enum Screen {
  ENTER_PERSONAL_INFORMATION = 'ENTER_PERSONAL_INFORMATION',
  START = 'START',
  WHERE_TO_CLEAN = 'WHERE_TO_CLEAN',
  CHOOSE_SERVICE = 'CHOOSE_SERVICE',
  HOME_DETAILS = 'HOME_DETAILS',
  CHOOSE_TIME = 'CHOOSE_TIME',
  CONFIRMATION = 'CONFIRMATION',
  CARD_DETAILS = 'CARD_DETAILS',
  BOOKINGS = 'BOOKINGS',
  LOGIN = 'LOGIN',
  NOT_AVAIABLE = 'NOT_AVAIABLE',
  PAYMENT_METHODS = 'PAYMENT_METHODS',
  SETTINGS = 'SETTINGS',
  FORGOTTEN_PASSWORD = 'FORGOTTEN_PASSWORD',
  CONTACT = 'CONTACT',
  ADDRESSES = 'ADDRESSES',
  ADD_ADDRESS = 'ADD_ADDRESS',
  NEW_BOOKING = 'NEW_BOOKING',
}

export default Screen;
