/* eslint-disable no-unused-vars */

enum Permission {
     ACCESS_TO_BACK_OFFICE = 'ACCESS_TO_BACK_OFFICE',

     // EMPLOYEES
     EMPLOYEE_CREATE = 'EMPLOYEE_CREATE',
     EMPLOYEE_UPDATE = 'EMPLOYEE_UPDATE',
     EMPLOYEE_LIST_ALL = 'EMPLOYEE_LIST_ALL',

     // CUSTOMER
     CUSTOMER_LIST_ALL = 'CUSTOMER_LIST_ALL',

     CUSTOMER_ADD_AND_BIND_ADDRESS = 'CUSTOMER_ADD_AND_BIND_ADDRESS',

     // Booking
     BOOKING_CREATE_BOOKING_TYPE = 'BOOKING_CREATE_BOOKING_TYPE',
     BOOKING_UPDATE_BOOKING_TYPE = 'BOOKING_UPDATE_BOOKING_TYPE',
     BOOKING_CREATE_ADDON = 'BOOKING_CREATE_ADDON',
     BOOKING_ADD_BOOKING_TO_CUSTOMER = 'BOOKING_ADD_BOOKING_TO_CUSTOMER',
     BOOKING_UPDATE_CUSTOMER_BOOKING = 'BOOKING_UPDATE_CUSTOMER_BOOKING',
     BOOKING_LIST_ALL_BOOKINGS = 'BOOKING_LIST_ALL_BOOKINGS',

     BOOKING_CANCEL_CUSTOMER_FRAME_BOOKING = 'BOOKING_CANCEL_CUSTOMER_FRAME_BOOKING',
     BOOKING_DELETE_CUSTOMER_BOOKING = 'BOOKING_DELETE_CUSTOMER_BOOKING',
     BOOKING_MARK_AS_COMPLETED = 'BOOKING_MARK_AS_COMPLETED',

     // Roles
     ROLE_LIST_ALL = 'ROLE_LIST_ALL',

     // ACCOUNT
     ACCOUNT_EDIT_ROLES = 'ACCOUNT_EDIT_ROLES',
     ACCOUNT_EDIT = 'ACCOUNT_EDIT',
     ACCOUNT_LIST_ALL = 'ACCOUNT_LIST_ALL'

}

export default Permission;
