  /booking/frame-booking:
    get:
      summary: Returns a list with all frame bookings

      produces:
        - application/json
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FrameBooking"