  /payment/card:
    get:
      summary: Get all cards
     
      produces:
        - application/json
      responses:
        200:
          description: OK
          content:
            application/json:
            schema:
                type: array
                items:
                  $ref: "#/components/schemas/CreditCard"
