  /booking/addon:
    post:
      summary: Creates a new addon
      consumes:
        - application/json
      parameters:
        - in: body
          name: CreateAddonRequest
          schema:
            type: object
            required:
              - name
              - defaultTimeInMinutes
              - description
            properties:
              name:
                type: string
              description:
                type: string
              defaultTimeInMinutes:
                type: number


      produces:
        - application/json
      responses:
        201:
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Addon"
        401:
            description: ACCESS_DENIED
        400:
            description: INVALID_INPUT
